### ISSUE TITLE
build cli command does not take root dir as an argument.

### ISSUE THREAD

**Issue by houd1ni** [farm-fe/farm#1197]
### Steps to reproduce

Take a look at https://www.farmfe.org/docs/cli/cli-api/#build
In vite `start` and `build` commands both take root dir.

### What is expected?

vite build works with only import.meta.env tuning.

### What is actually happening?

It crashes:
```
> menu-front@0.0.1 my-build-client
> cross-env APP=d farm build ./my -c ./my/farm.config.ts

[ Farm ] Using config file at C:\Users\houd1ni\front\my\farm.config.ts
[ Farm ] Build failed due to errors: Can not resolve index.html  from undefined.
Error: ENOENT: no such file or directory, stat 'C:\Users\houd1ni\front\index.html'
    at Object.statSync (node:fs:1660:25)
    at checkCompilationInputValue (file:///C:/Users/houd1ni/front/node_modules/@farmfe/core/dist/config/index.js:645:24)
    at normalizeUserCompilationConfig (file:///C:/Users/houd1ni/front/node_modules/@farmfe/core/dist/config/index.js:116:30)
    at resolveConfig (file:///C:/Users/houd1ni/front/node_modules/@farmfe/core/dist/config/index.js:88:44)
    at async build (file:///C:/Users/houd1ni/front/node_modules/@farmfe/core/dist/index.js:41:32)
    at async handleAsyncOperationErrors (file:///C:/Users/houd1ni/front/node_modules/@farmfe/cli/dist/utils.js:111:9)
[ building ] ⠂ transform (110) node_modules/core-js/internals/object-get-prototype-of.js.farm-runtime
[ Farm ] Error: Can not resolve `` from C:\Users\houd1ni\front.
Original error: None.

Potential Causes:
1.The file that `` points to does not exist.
2.Install it first if `` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm.io/faq#pnpm-does-not-work-with-your-project-here] for solutions.
3. If `` is a alias, make sure your alias config is correct.
```

### System Info

```Shell
Win10x64 Pro latest, Intel 14600kf, 32Gb ram, almost empty.
```

**Comment by ErKeLost** [comment]
i will try it

**Comment by ErKeLost** [comment]
fixed with 1.1.0
