### ISSUE TITLE
[Bug Report]: build error

### ISSUE THREAD

**Issue by callqh** [farm-fe/farm#1328]
### Steps to reproduce

1. run build

### Reproduce link

https://github.com/jstors/farm-react-admin

### What is actually happening?

```shell

[ building ] ⠈ transform (1716) node_modules/.pnpm/@arco-design+web-react@2.61.3_@types+react@18.2.78_rea[ Farm ] Failed to build: Error: Transform `src/pages/login/types.ts` failed.
Error: This experimental syntax requires enabling one of the following parser plugin(s): "flow", "typescript". (2:7)
SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): "flow", "typescript". (2:7)
    at constructor (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:353:19)
    at JSXParserMixin.raise (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:3277:19)
    at JSXParserMixin.expectOnePlugin (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:3311:18)
    at JSXParserMixin.isExportDefaultSpecifier (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:13411:16)
    at JSXParserMixin.maybeParseExportDefaultSpecifier (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:13313:40)
    at JSXParserMixin.parseExport (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:13253:29)
    at JSXParserMixin.parseStatementContent (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12352:27)
    at JSXParserMixin.parseStatementLike (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12239:17)
    at JSXParserMixin.parseModuleItem (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12216:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12796:36)
Transform `src/pages/login/index.tsx` failed.
Error: Unexpected token, expected "{" (10:7)
SyntaxError: Unexpected token, expected "{" (10:7)
    at constructor (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:353:19)
    at JSXParserMixin.raise (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:3277:19)
    at JSXParserMixin.unexpected (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:3297:16)
    at JSXParserMixin.parseExport (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:13307:10)
    at JSXParserMixin.parseStatementContent (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12352:27)
    at JSXParserMixin.parseStatementLike (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12239:17)
    at JSXParserMixin.parseModuleItem (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12216:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12796:36)
    at JSXParserMixin.parseBlockBody (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12789:10)
    at JSXParserMixin.parseProgram (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12116:10)
Transform `src/hooks/useRouterGuard.ts` failed.
Error: Unexpected token, expected "," (6:47)
SyntaxError: Unexpected token, expected "," (6:47)
    at constructor (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:353:19)
    at JSXParserMixin.raise (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:3277:19)
    at JSXParserMixin.unexpected (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:3297:16)
    at JSXParserMixin.expect (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:3601:28)
    at JSXParserMixin.parseBindingList (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:7180:14)
    at JSXParserMixin.parseFunctionParams (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12935:24)
    at JSXParserMixin.parseFunction (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12917:10)
    at JSXParserMixin.parseExportDefaultExpression (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:13369:19)
    at JSXParserMixin.parseExport (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:13297:25)
    at JSXParserMixin.parseStatementContent (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12352:27)
Transform `src/utils/cookie.ts` failed.
Error: Unexpected token, expected "," (44:32)
SyntaxError: Unexpected token, expected "," (44:32)
    at constructor (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:353:19)
    at JSXParserMixin.raise (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:3277:19)
    at JSXParserMixin.unexpected (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:3297:16)
    at JSXParserMixin.expect (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:3601:28)
    at JSXParserMixin.parseBindingList (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:7180:14)
    at JSXParserMixin.parseFunctionParams (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12935:24)
    at JSXParserMixin.parseFunction (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12917:10)
    at JSXParserMixin.parseFunctionStatement (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12602:17)
    at JSXParserMixin.parseStatementContent (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12263:21)
    at JSXParserMixin.parseStatementLike (/Users/liuqh/lqh/farm-react-admin/node_modules/.pnpm/@babel+parser@7.24.4/node_modules/@babel/parser/lib/index.js:12239:17)
 ELIFECYCLE  Command failed with exit code 1.
```

### System Info

```Shell
/
```

**Comment by callqh** [comment]
`@farmfe/core`Version 1.1.2 does not have this issue, the problem appeared after upgrading to the new version.

**Comment by shulandmimi** [comment]
This plugin seems to only support transform js and css. You can use it to see if it meets your needs.

```ts
{
	// ..
	vitePlugins: [
		() => ({
	      filters: ['.js$', '.css$'],
	        vitePlugin: vitePluginForArco({
	          theme: '@arco-themes/react-juzi001',
	        })
	    }),
	]
}
```

**Comment by callqh** [comment]
> This plugin seems to only support transform js and css. You can use it to see if it meets your needs.
> 
> ```ts
> {
> 	// ..
> 	vitePlugins: [
> 		() => ({
> 	      filters: ['.js$', '.css$'],
> 	        vitePlugin: vitePluginForArco({
> 	          theme: '@arco-themes/react-juzi001',
> 	        })
> 	    }),
> 	]
> }
> ```

This configuration cannot run properly.

**Comment by shulandmimi** [comment]
This plugin requires typescript to be compiled before it or itself
