### ISSUE TITLE
[Bug Report]: `vanilla-extract` can't run twice

### ISSUE THREAD

**Issue by fu050409** [farm-fe/farm#1659]
### Steps to reproduce

Run `pnpm dev` twice.

### Reproduce link

https://github.com/farm-fe/farm/tree/main/examples/vanilla-extract

### What is actually happening?

```console
$ pnpm dev
[ building ] ⠂ load cached module(19) ../../packages/runtime-plugin-hmr/src/index.ts.farm-runtime                                                          
[ Farm ] Error: Failed to start the server
Caused by: Error: Can not resolve `C:/Users/nocti/Desktop/Workspace/farm/examples/vanilla-extract/src/styles.css.ts.vanilla.css` from src/styles.css.ts.
Original error: Some(NAPIError("No CSS for file: C:/Users/nocti/Desktop/Workspace/farm/examples/vanilla-extract/src/styles.css.ts\nError: No CSS for file: C:/Users/nocti/Desktop/Workspace/farm/examples/vanilla-extract/src/styles.css.ts\n    at Object.getCssForFile (C:\\Users\\nocti\\Desktop\\Workspace\\farm\\node_modules\\.pnpm\\@vanilla-extract+integration@7.1.7_@types+node@20.12.12_babel-plugin-macros@3.1.0_less@4.2.0__tzx2r3t6zn2nz6ce7g57ft3cm4\\node_modules\\@vanilla-extract\\integration\\dist\\vanilla-extract-integration.cjs.dev.js:853:15)\n    at Object.resolveId (C:\\Users\\nocti\\Desktop\\Workspace\\farm\\node_modules\\.pnpm\\@vanilla-extract+vite-plugin@4.0.13_@types+node@20.12.12_babel-plugin-macros@3.1.0_less@4.2.0_xrgsgvuzgczc37zwrjwwkjtu6q\\node_modules\\@vanilla-extract\\vite-plugin\\dist\\vanilla-extract-vite-plugin.cjs.dev.js:187:79)\n    at file:///C:/Users/nocti/Desktop/Workspace/farm/packages/core/dist/plugin/js/vite-plugin-adapter.js:207:51\n    at file:///C:/Users/nocti/Desktop/Workspace/farm/packages/core/dist/plugin/js/vite-plugin-adapter.js:151:30")).

Potential Causes:
1.The file that `C:/Users/nocti/Desktop/Workspace/farm/examples/vanilla-extract/src/styles.css.ts.vanilla.css` points to does not exist.
2.Install it first if `C:/Users/nocti/Desktop/Workspace/farm/examples/vanilla-extract/src/styles.css.ts.vanilla.css` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm.io/faq#pnpm-does-not-work-with-your-project-here] for solutions.
3. If `C:/Users/nocti/Desktop/Workspace/farm/examples/vanilla-extract/src/styles.css.ts.vanilla.css` is a alias, make sure your alias config is correct.   

    at logError (file:///C:/Users/nocti/Desktop/Workspace/farm/packages/core/dist/server/error.js:74:15)
    at Server.compile (file:///C:/Users/nocti/Desktop/Workspace/farm/packages/core/dist/server/index.js:62:29)
    at async Server.listen (file:///C:/Users/nocti/Desktop/Workspace/farm/packages/core/dist/server/index.js:44:9)
    at async start (file:///C:/Users/nocti/Desktop/Workspace/farm/packages/core/dist/index.js:31:9)
    at async handleAsyncOperationErrors (file:///C:/Users/nocti/Desktop/Workspace/farm/packages/cli/dist/utils.js:111:9)
 ELIFECYCLE  Command failed with exit code 1.
```

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i9-13900H
    Memory: 3.84 GB / 15.64 GB
  Binaries:
    Node: 21.6.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.3.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.6.0 - ~\AppData\Local\pnpm\pnpm.CMD
    bun: 1.0.31 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (126.0.2592.113)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @farmfe/core: workspace:* => 1.3.9
```

**Comment by Su-Yong** [comment]
It seems to be affected by `persistentCache`.
If you set `compilation.persistentCache` as false, the plugin now works.
