### ISSUE TITLE
[Bug Report]: "Cannot redefine property: init..." on versions after @farmfe/core 1.3.12

### ISSUE THREAD

**Issue by Micnubinub** [farm-fe/farm#1755]
### Steps to reproduce

My code builds and serves just fine on `@farmfe/core 1.3.12`, but all versions from `.13-.16` give the issue below. Here are the packages I'm using:
```json
"@farmfe/cli": "1.0.4",
"@farmfe/core": "1.3.16",
"@farmfe/js-plugin-postcss": "1.8.0",
"@farmfe/plugin-react": "1.2.1",
"@sentry/node": "8.27.0",
"@sentry/react": "8.27.0",
"@sentry/vite-plugin": "2.22.3",
```

### What is actually happening?

Failed to build or serve live

```js
Uncaught TypeError: Cannot redefine property: init
    at Function.defineProperty (<anonymous>)
    at Module.o ((index):725:16)
    at Module.d ((index):731:14)
    at Module._ ((index):787:14)
    at ../node_modules/@sentry/react/build/esm/index.js (index_80fa.js:3864:12)
    at ModuleSystem.require ((index):1010:26)
    at src/stores/common.ts (index_8e79.js:4635:29)
    at ModuleSystem.require ((index):1010:26)
    at src/forms/UserProfileForm.tsx (index_8e79.js:1742:30)
    at ModuleSystem.require ((index):1010:26)
```

### System Info

```Shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 78.08 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.7.0 - /opt/homebrew/bin/node
    npm: 10.8.0 - /opt/homebrew/bin/npm
    bun: 1.1.26 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 128.0.6613.114
    Safari: 17.6
  npmPackages:
    @farmfe/core: 1.3.16 => 1.3.16
```

**Comment by wre232114** [comment]
I'll take a look, thanks for reporting issues

**Comment by airset-au** [comment]
Any update on this issue?

**Comment by wre232114** [comment]
It will be fixed in `@farmfe/core@1.3.26`

**Comment by Micnubinub** [comment]
Still getting the issue on:
```json
"@sentry/node": "8.34.0",
"@sentry/react": "8.34.0",
"@sentry/vite-plugin": "2.22.5",
"@farmfe/cli": "1.0.4",
"@farmfe/core": "1.3.26",
"@farmfe/js-plugin-postcss": "1.8.1",
"@farmfe/plugin-react": "1.2.3"
```

**Comment by wre232114** [comment]
I missed a package when publishing packages, I'll publish it with @farmfe/core@1.2.27

**Comment by wre232114** [comment]
@farmfe/core@1.2.27 released, it should work as expected now

**Comment by Micnubinub** [comment]
Looks good now🥳
