### ISSUE TITLE
[Bug Report]: farm start error

### ISSUE THREAD

**Issue by stack-stark** [farm-fe/farm#1785]
### Steps to reproduce

1.npm create farm@latest
2. Select Framework vue3
3. cd dir && npm i 
4. npm run dev 

### What is actually happening?

[ Farm ] Error: Failed to start the server
Caused by: Error: Transform `src/App.vue` failed.
Error: Vite plugin 'vite:vue' is not compatible with Farm for now. Because it uses viteConfig['esbuild'] which is not supported by Farm. Current supported keys are: root,base,publicDir,mode,define,command,resolve,plugins,server,isProduction,css,build,logger,cacheDir,envDir,assetsInclude,legacy,optimizeDeps,ssr,logLevel,experimental,test,clearScreen,customLogger,configFile,inlineConfig
Error: Vite plugin 'vite:vue' is not compatible with Farm for now. Because it uses viteConfig['esbuild'] which is not supported by Farm. Current supported keys are: root,base,publicDir,mode,define,command,resolve,plugins,server,isProduction,css,build,logger,cacheDir,envDir,assetsInclude,legacy,optimizeDeps,ssr,logLevel,experimental,test,clearScreen,customLogger,configFile,inlineConfig
    at throwIncompatibleError (file:///D:/demo/farmvue/farmvue/node_modules/@farmfe/core/dist/plugin/js/utils.js:174:11)
    at getTargetField (file:///D:/demo/farmvue/farmvue/node_modules/@farmfe/core/dist/plugin/js/farm-to-vite-config.js:99:11)
    at Object.get (file:///D:/demo/farmvue/farmvue/node_modules/@farmfe/core/dist/plugin/js/farm-to-vite-config.js:195:20)
    at transformMain (file:///D:/demo/farmvue/farmvue/node_modules/@vitejs/plugin-vue/dist/index.mjs:2564:37)
    at async file:///D:/demo/farmvue/farmvue/node_modules/@farmfe/core/dist/plugin/js/vite-plugin-adapter.js:302:32
    at async file:///D:/demo/farmvue/farmvue/node_modules/@farmfe/core/dist/plugin/js/vite-plugin-adapter.js:151:24
    at logError (file:///D:/demo/farmvue/farmvue/node_modules/@farmfe/core/dist/server/error.js:74:15)
    at Server.compile (file:///D:/demo/farmvue/farmvue/node_modules/@farmfe/core/dist/server/index.js:63:29)
    at async Server.listen (file:///D:/demo/farmvue/farmvue/node_modules/@farmfe/core/dist/server/index.js:45:9)
    at async start (file:///D:/demo/farmvue/farmvue/node_modules/@farmfe/core/dist/index.js:35:9)
    at async handleAsyncOperationErrors (file:///D:/demo/farmvue/farmvue/node_modules/@farmfe/cli/dist/utils.js:111:9)
![20240920153037](https://github.com/user-attachments/assets/1f17223c-9af3-4d3c-b876-45461531adae)

### System Info

```Shell
os: win11 
node -v: v20.10.0
"dependencies": {
  "vue": "^3.4.0"
},
"devDependencies": {
    "@farmfe/cli": "^1.0.2",
    "@farmfe/core": "^1.3.0",
    "@vitejs/plugin-vue": "^5.0.4",
    "core-js": "^3.30.1"
  }
```

**Comment by fu050409** [comment]
Thanks for your report and we will fix this as soon as possible

**Comment by fu050409** [comment]
This error is caused by the updates in new version of `@vitejs/plugin-vue`, a temp solution is to bump your `@vitejs/plugin-vue` to exact version `5.0.4`, modify your `package.json` and replace `"@vitejs/plugin-vue": "^5.0.4"` with `"@vitejs/plugin-vue": "5.0.4"` (remove `^` prefix).

**Comment by stack-stark** [comment]
嗯好 我试试

**Comment by ErKeLost** [comment]
@stack-stark @farmfe/core: 1.3.23 已经修复
