### ISSUE TITLE
[Bug Report]: Rust plugin template arm linux builds fail

### ISSUE THREAD

**Issue by ssttevee** [farm-fe/farm#1931]
### Steps to reproduce

1. `pnpm create farm-plugin my-farm-plugin --type rust`
2. `git push`

### What is actually happening?

```
... omitted ...

error: /home/runner/work/farm-plugin-resources-import-meta/farm-plugin-resources-import-meta/target/aarch64-unknown-linux-musl/release/deps/libserde_json-013ad71daae11659.rlib: unrecognized file extension

error: could not compile `browserslist-rs` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
You are cross compiling aarch64-unknown-linux-musl on linux host
Internal Error: Command failed: cargo build --release --target aarch64-unknown-linux-musl -p farm_plugin_resources_import_meta
    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at BuildCommand.<anonymous> (/home/runner/work/farm-plugin-resources-import-meta/farm-plugin-resources-import-meta/node_modules/.pnpm/@napi-rs+cli@2.18.4/node_modules/@napi-rs/cli/scripts/index.js:11529:30)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/farm-plugin-resources-import-meta/farm-plugin-resources-import-meta/node_modules/.pnpm/@napi-rs+cli@2.18.4/node_modules/@napi-rs/cli/scripts/index.js:3523:56)

```

Example log https://github.com/ssttevee/farm-plugin-resources-import-meta/actions/runs/11770730991/job/32783592935

### System Info

```Shell
N/A
```

**Comment by wre232114** [comment]
I'll take a look, the plugin template may need to be updated

**Comment by wre232114** [comment]
see this example, the ci scripts needs to be updated. https://github.com/farm-fe/rust-plugin-example/pull/4. I'll update the plugin template today
