### ISSUE TITLE
启动问题

### ISSUE THREAD

**Issue by tzwhyqq** [farm-fe/farm#229]
### Steps to reproduce

npm run dev

### What is expected?

[ Farm ] Using config file at D:\TestProject\vue\farm.config.ts
file:///C:/Users/ADMINI~1/AppData/Local/Temp/farmfe/1981e00ecdc26be4ad693d93ebe305b8/farm.config.bundle.mjs:46134
                "hack": `true;@import "${require.resolve("ant-design-vue/lib/style/color/colorPalette.less")}";`,
                                                 ^

TypeError: require.resolve is not a function
    at getThemeVariables (file:///C:/Users/ADMINI~1/AppData/Local/Temp/farmfe/1981e00ecdc26be4ad693d93ebe305b8/farm.config.bundle.mjs:46134:50)
    at generateModifyVars (file:///C:/Users/ADMINI~1/AppData/Local/Temp/farmfe/1981e00ecdc26be4ad693d93ebe305b8/farm.config.bundle.mjs:529:61)
    at 196952fc (file:///C:/Users/ADMINI~1/AppData/Local/Temp/farmfe/1981e00ecdc26be4ad693d93ebe305b8/farm.config.bundle.mjs:591:80)
    at ModuleSystem.require (file:///C:/Users/ADMINI~1/AppData/Local/Temp/farmfe/1981e00ecdc26be4ad693d93ebe305b8/farm.config.bundle.mjs:104:17)
    at file:///C:/Users/ADMINI~1/AppData/Local/Temp/farmfe/1981e00ecdc26be4ad693d93ebe305b8/farm.config.bundle.mjs:46161:30
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async readConfigFile (file:///D:/TestProject/vue/node_modules/.pnpm/registry.npmmirror.com+@farmfe+core@0.6.3/node_modules/@farmfe/core/dist/config/index.js:240:25)
    at async resolveUserConfig (file:///D:/TestProject/vue/node_modules/.pnpm/registry.npmmirror.com+@farmfe+core@0.6.3/node_modules/@farmfe/core/dist/config/index.js:147:28)

 require.resolve

### What is actually happening?

这个要怎么解决吗

### System Info

```Shell
win10
vue3
node16
使用的测试前端框架 vben-admin
```

**Comment by wre232114** [comment]
将配置文件从 farm.config.ts 改成 farm.config.js（ts 后缀改成 js 后缀）

**Comment by tzwhyqq** [comment]
改了出现新的问题 
SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)

**Comment by wre232114** [comment]
如果在 farm.config.js 里面用了 import 等 esm 语法，那就改成 farm.config.mjs（后缀改成 mjs)

**Comment by tzwhyqq** [comment]
试了，也是其他错误。搞不定，方便留个邮箱看看吗

**Comment by wre232114** [comment]
1521488775@qq.com
